### ISSUE TITLE
Crashing when setting WebView as ignoredViews

### ISSUE THREAD

**Issue by scm573** [Karumi/Shot#114]
### Expected behaviour
Screenshot can be taken when setting WebView as ignoredViews

### Actual behaviour
Test crashes

### Steps to reproduce
・Set WebView as ignoredViews
・Call compareScreenshot() method in the test case

Here's the stacktrace:

java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'Instr: com.karumi.shot.ShotTestRunner'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {2d8403a} called on null, FYI main Looper is Looper (main, tid 2) {2d8403a})
at android.webkit.WebView.checkThread(WebView.java:2700)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2672)
at android.webkit.WebView.onVisibilityChanged(WebView.java:3019)
at android.view.View.dispatchVisibilityChanged(View.java:12819)
at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1539)
at android.view.View.setFlags(View.java:14167)
at android.view.View.setVisibility(View.java:9992)
at com.karumi.shot.ScreenshotTest$DefaultImpls.hideIgnoredViews(ScreenshotTest.kt:106)
at com.karumi.shot.ScreenshotTest$DefaultImpls.disableFlakyComponentsAndWaitForIdle(ScreenshotTest.kt:100)

### Version of the library
4.2.0

**Comment by pedrovgs** [comment]
This one is really easy to fx. We only need to move the view handling the ignored view to the target app thread. It will be fixed for the next release. Thanks for reporting @scm573

**Comment by pedrovgs** [comment]
Hi @scm573 I've released a new version with the fix for this crash. As soon as the version 4.3.0 is indexed by Maven Central you'll be able to use it 😃
