### ISSUE TITLE
downloadScreenshot failed in devices with API >=29

### ISSUE THREAD

**Issue by SisterMorphine** [Karumi/Shot#120]
When executing the Screenshot tests, the tests are actually executed in the emulator but then the gradle tasks fails when downloading screenshots

```java
`$ ./gradlew executeScreenshotTests --stacktrace
`
> Task :designsystemdemoapp:connectedDebugAndroidTest
Starting 25 tests on Pixel_3a_API_Q(AVD) - 10

> Task :designsystemdemoapp:downloadScreenshots FAILED
⬇️  Pulling screenshots from your connected devices!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':designsystemdemoapp:downloadScreenshots'.
> Nonzero exit value: 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':designsystemdemoapp:downloadScreenshots'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: Nonzero exit value: 1
        at scala.sys.package$.error(package.scala:27)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:134)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:104)
        at com.karumi.shot.android.Adb.executeAdbCommandWithResult(Adb.scala:33)
        at com.karumi.shot.android.Adb.pullScreenshots(Adb.scala:23)
        at com.karumi.shot.Shot.$anonfun$pullScreenshots$1(Shot.scala:121)
        at com.karumi.shot.Shot.$anonfun$pullScreenshots$1$adapted(Shot.scala:118)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at com.karumi.shot.Shot.pullScreenshots(Shot.scala:118)
        at com.karumi.shot.Shot.$anonfun$downloadScreenshots$1(Shot.scala:40)
        at com.karumi.shot.Shot.$anonfun$downloadScreenshots$1$adapted(Shot.scala:38)
        at com.karumi.shot.Shot.executeIfAppIdIsValid(Shot.scala:103)
        at com.karumi.shot.Shot.downloadScreenshots(Shot.scala:38)
        at com.karumi.shot.tasks.DownloadScreenshotsTask.downloadScreenshots(Tasks.scala:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more`

```

**Comment by pedrovgs** [comment]
Hi @SisterMorphine looks like there is something wrong with your emulator or with your code. Did you create the emulator with an SD card? Is your project configured with the expected permissions in the test ``AndoridManifest.xml``.  Please, review the project ``README.md`` and ensure you followed every step.

**Comment by SisterMorphine** [comment]
Hi!

AndroidManifest has the permission android.permission.WRITE_EXTERNAL_STORAGE

These are the commands to create the emulator: 

1/ Download Android 29 image:
$ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-29;google_apis_playstore;x86'
2/ Create Pixel XL emulator:
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis_playstore;x86' -d "pixel_xl" --force

**Comment by pedrovgs** [comment]
@SisterMorphine looks like you are not configuring the sdcard needed in your emulator. Look at the example script we provide to create the emulator: https://github.com/Karumi/Shot/blob/master/shot-consumer/scripts/create_emulator.sh#L18

Could you configure the SD card and try the execution again?

**Comment by harneeksingh27** [comment]
I have the same problem but only on API 29 only, on rest of the emulators it works fine.
I am creating emulators through and manager of A.S
Could API level be the problem?

**Comment by pedrovgs** [comment]
@harneeksingh27 can you check if you configured the SD card?

**Comment by harneeksingh27** [comment]
Yes SD card is configured for sure, as I Created manually I have added sd card to the emulator

**Comment by pedrovgs** [comment]
@SisterMorphine could you confirm if the issue is related to the sd card?

@harneeksingh27 could you please try with another android API emulator. With API 28 just to check if the issue is related to Android 29 or not.

**Comment by harneeksingh27** [comment]
@pedrovgs I checked on emulator  with API 28 and 26 it worked like a charm.
I created emulator with API 29 and even Android R and I got this error 
⬇️  Pulling screenshots from your connected devices!

So I was stuck on this issue since 3 -4 weeks and I had no clue what is going on(I was using api 29). I read all of the issues logged in this repo one by one.
Accidentally I had api 28 emulator open and I triggered tests without realising it, and it worked.

Did u guys ever checked this on API 29 and above?

**Comment by pedrovgs** [comment]
Nope, I had no time to test shot in API 29.

**Comment by SisterMorphine** [comment]
@pedrovgs It seems that the error it's related with the SD, indeed. Following your script example I could create the device with SD and then I avoided the error.

However it seems I am not able get rid of the problem when I try to use an emulator with specific model, it seems like the card is not successfully attached when I use an emulator with defined model like this:
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis_playstore;x86' -d "pixel_xl" --force

Thanks!

**Comment by pedrovgs** [comment]
@SisterMorphine looks like you can't get rid of the problem because you are not using the sd card when creating the emulator. The param ``--sdcard <PATH_TO_YOUR_SD_CARD>`` is not in the command you pasted, is it?

**Comment by SisterMorphine** [comment]
@pedrovgs Copy paste error I guess, but this is how I created it: 
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis_playstore;x86' -d "pixel_xl" --force  --sdcard sdcard.img

Also I tried this way:
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis_playstore;x86' -d "pixel_xl" -c 1000M --force

**Comment by harneeksingh27** [comment]
Coincidently I am also trying api 29 on PIXEL_3a

**Comment by pedrovgs** [comment]
@SisterMorphine can you try with an android-28 device?

**Comment by SisterMorphine** [comment]
@pedrovgs I got the same error with android-28: 

rm -rf sdcard.img
$ANDROID_HOME/emulator/mksdcard -l e 1G sdcard.img
$ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-28;google_apis_playstore;x86'
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k "system-images;android-26;google_apis;x86" -d "pixel_xl" --force  --sdcard sdcard.img

<img width="1004" alt="Screenshot 2020-06-15 at 10 30 20" src="https://user-images.githubusercontent.com/5555861/84635436-8206ef80-aef3-11ea-9f37-a1df8e9e5095.png">

**Comment by pedrovgs** [comment]
@SisterMorphine we need to continue checking your project configuration. Could you create a repository with the same configuration you have in the project you are trying to use Shot reproducing the error?

**Comment by SisterMorphine** [comment]
Hi, I tested in this repository
https://github.com/PabloMGrela/kotlin_clean_mvp
with the following sequence of commands, having the same error result: 
1. Create emulator
$ANDROID_HOME/tools/bin/avdmanager create avd -n android_emulator -k 'system-images;android-29;google_apis_playstore;x86' -d "pixel_xl" -c 1000M --force
2. Start emulator
nohup $ANDROID_HOME/emulator/emulator -avd android_emulator -no-snapshot > /dev/null 2>&1 &
3. Deactivate animations:
$ANDROID_HOME/platform-tools/adb shell settings put global window_animation_scale 0
$ANDROID_HOME/platform-tools/adb shell settings put global transition_animation_scale 0
$ANDROID_HOME/platform-tools/adb shell settings put global animator_duration_scale 0
4. Switch off connectivty:
$ANDROID_HOME/platform-tools/adb shell svc data disable
$ANDROID_HOME/platform-tools/adb shell svc wifi disable
5. Execute tests
./gradlew executeScreenshotTests

**Comment by pedrovgs** [comment]
@SisterMorphine I've cloned the mentioned repository and execute the tests in the emulator you created and everything worked. What OS are you using? Is there anybody in your team who can reproduce the error?

**Comment by SisterMorphine** [comment]
@pedrovgs It seems that is only happening to me. I was using Mojave and recently changed to Catalina, and nothing changed. 

Thank you very much for your help

**Comment by pedrovgs** [comment]
@SisterMorphine could you please using your laptop debug what's going on and check why the plugin is not working in your laptop? You can find the development documentation in the project readme.

**Comment by harneeksingh27** [comment]
I still have the issue on Api 29, I am clueless regarding what is going wrong 🦺

**Comment by hkosacki** [comment]
I can confirm that the issue is also reproducible on my end using Android Q and R. For P it seems to be working fine (all are emulators).

**Comment by gioPucela** [comment]
We are using shot 3.1.0 and com.trevjonez.composer:plugin:1.0.0-rc05
shot {
    appId = 'our_app_id'
    instrumentationTestTask = "testDebugComposer"
}

and getting the same error
However, if we comment out the instrumentationTestTask, it just works fine

**Comment by pedrovgs** [comment]
Hey @hkosacki as you can reproduce this error, could you create a sample project reproducing this error. You can use github actions to configure the emulators you mention. Once the sample repository is ready I'll personally review what's going on and fix the issue.

**Comment by felipecastilhos** [comment]
Hi @pedrovgs, I'm facing the same issue here. 

https://github.com/felipecastilhos/ShotThis

this is a simple project trying to test a default android project with a single activity. I have the same error in every emulator I run the tests.

I created 2 emulators using the AVD Manager GUI in Android Studio. I setup a emulator with API 28, after reading this thread i tryed on a API 26 emulator and got the same error. I do not have the GitHub Actions configured, but you can run my project if you want it.

My emulator config:
`
 Name: Pixel_2_API_27 CPU/ABI: Google Play Intel Atom (x86)  Target: google_apis_playstore [Google Play] (API level 27) Skin: pixel_2 SD Card: 512M fastboot.chosenSnapshotFile: runtime.network.speed: full hw.accelerometer: yes hw.device.name: pixel_2 hw.lcd.width: 1080 hw.initialOrientation: Portrait image.androidVersion.api: 27 tag.id: google_apis_playstore hw.mainKeys: no hw.camera.front: emulated avd.ini.displayname: Pixel 2 API 27 hw.gpu.mode: auto hw.ramSize: 1536 PlayStore.enabled: true fastboot.forceColdBoot: no hw.cpu.ncore: 4 hw.keyboard: yes hw.sensors.proximity: yes hw.dPad: no hw.lcd.height: 1920 vm.heapSize: 256 skin.dynamic: yes hw.device.manufacturer: Google hw.gps: yes hw.audioInput: yes image.sysdir.1: system-images/android-27/google_apis_playstore/x86/ showDeviceFrame: yes hw.camera.back: virtualscene AvdId: Pixel_2_API_27 hw.lcd.density: 420 hw.arc: false hw.device.hash2: MD5:55acbc835978f326788ed66a5cd4c9a7 fastboot.forceChosenSnapshotBoot: no fastboot.forceFastBoot: yes hw.trackBall: no hw.battery: yes hw.sdCard: yes tag.display: Google Play runtime.network.latency: none disk.dataPartition.size: 6442450944 hw.sensors.orientation: yes avd.ini.encoding: UTF-8 hw.gpu.enabled: yes`

**Comment by MrXlebNick** [comment]
Hi @pedrovgs, I'm having the same issue and I went ahead and created a GitHub Actions with this issue reproduced: https://github.com/MrXlebNick/shot-fragmentscenario/runs/1036649443

**Comment by MrXlebNick** [comment]
Eventually I was able to make it succeed once in the test repo: https://github.com/MrXlebNick/shot-fragmentscenario/runs/1047402932?check_suite_focus=true.

Some breadcrumbs and thoughts about making it work:

- I wasn't able to run it without DexOpener no matter what I did
- The first successful run was after removing `androidTest/AndroidManifest.xml`
- ConstraintLayout was behaving weirdly showing empty screenshots, switching to LinearLayout helped
- The process is still flaky, it can fail or success on its own. I still can't stably reproduce success in GitHub Actions
- `./gradlew clean` and removing freshly generated screenshots folder from the repo increases chances for successful
- I can succeed the screenshot record locally with almost 100% guarantee, but not in GitHub Actions

**Comment by pedrovgs** [comment]
Ok, I have a nice update. I've checked the example provided by @felipecastilhos and I can ensure the project is working for emulators API <=28. There is an issue when the API is >=29 and I'm going to rename this issue to ensure there are no misleading about it. I've sent a PR https://github.com/felipecastilhos/ShotThis/pull/1 fixing @felipecastilhos's repository and here you have a gif showing how Shot can be executed with this project or any properly configured project in an emulator with API <=28.


https://drive.google.com/file/d/1F4jM4assrVCzhRvphku8_A-z-SDWiMN7/view?usp=sharing


The issue with the API >=29 is related to the new storage management we do not support for now. However, if anyone would like to contribute, it could be awesome 😃

**Comment by anhduy5689h** [comment]
API 30 has new permission: MANAGE_EXTERNAL_STORAGE. So, we must open the Settings application to grant this permission by hand.

**Comment by diarmaidlindsay** [comment]
Our Shot tests no longer work since we began targeting API 30, and I've been trying to work around this for the past few days without success.

> API 30 has new permission: MANAGE_EXTERNAL_STORAGE. So, we must open the Settings application to grant this permission by hand.

I was thinking perhaps it would be possible to 
`adb shell pm grant <test-package> android.permission.MANAGE_EXTERNAL_STORAGE`
during the test execution, similar to what was done here [HERE](https://gist.github.com/RussellCollins/87e447183103fe6ca8b1)

**Comment by pedrovgs** [comment]
🤔  Did someone try adding MANAGE_EXTERNAL_STORAGE to the testing manifest?

**Comment by mbarrben** [comment]
> 🤔 Did someone try adding MANAGE_EXTERNAL_STORAGE to the testing manifest?

We're not currently using Shot, but this maybe helps. We have a custom solution with `UiAutomation.takeScreenshot()` plus [Composer](https://github.com/gojuno/composer) to pull the screenshots from the emulator and generate the report. Once we targeted API 30, we needed to add the `MANAGE_EXTERNAL_STORAGE` permission to the testing manifest to be able to store the screenshots in the public external storage so Composer could later pull them.

**Comment by pedrovgs** [comment]
I don't think that's going to work out of the box @mbarrben. You'd need to add the permission and grant it from your tests. I'd also need to review if this works when it is configured. However, if any of you would like to try it out, that'd be great!

**Comment by pedrovgs** [comment]
I have great news!!!
