### ISSUE TITLE
RuntimeException exception while executing a screenshot test

### ISSUE THREAD

**Issue by LalitSharma-Systango** [Karumi/Shot#123]
## Description
Test cases are failing with following error:
Can't create handler inside thread that has not called Looper.prepare()

## Error Log

```
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.content.ClipboardManager$2.<init>(ClipboardManager.java:69)
at android.content.ClipboardManager.<init>(ClipboardManager.java:69)
at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:231)
at android.app.SystemServiceRegistry$10.createService(SystemServiceRegistry.java:230)
at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:849)
at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:799)
at android.app.ContextImpl.getSystemService(ContextImpl.java:1550)
at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:171)
at android.app.Activity.getSystemService(Activity.java:5767)
at android.widget.TextView.canPaste(TextView.java:9629)
at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:9106)
at android.widget.EditText.onInitializeAccessibilityNodeInfoInternal(EditText.java:147)
at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6553)
at androidx.core.view.ViewCompat.onInitializeAccessibilityNodeInfo(ViewCompat.java:656)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.createNodeInfoFromView(AccessibilityUtil.java:179)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.createNodeInfoFromView(AccessibilityUtil.java:156)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.access$000(AccessibilityUtil.java:41)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil$AXTreeNode.<init>(AccessibilityUtil.java:601)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:580)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.layouthierarchy.AccessibilityUtil.generateAccessibilityTree(AccessibilityUtil.java:585)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.record(ScreenshotImpl.java:277)
at com.facebook.testing.screenshot.internal.RecordBuilderImpl.record(RecordBuilderImpl.java:153)
```

What I have noticed is that, the test cases are failing only for the screens where we have a edittext input type with soft keyboard open on the screen.

The version that I am using is the updated one i.e. 4.3.0.

## Following is a code snippet that I am using

   ```
@Test
    fun testDefault() {
        val arrayList = ArrayList<StepValue>()
        arrayList.add(SomeObject(valueId, null, "", "", "", ArrayList()))
        arrayList.add(SomeObject(frequencyValueId, null, "", "", "", getDummyList()))
        var stepResponse = SomeObject("", instruction, SomeObject, description, "", progress, "", arrayList)
        val intent = Intent()
        intent.putExtra(Constants.IntentExtras.NEXT_STEP, stepResponse)
        val activity = activityTestRule.launchActivity(intent)
        Screenshot.snapActivity(activity).setName(name + "Default").record()
    }

```

Let me know if you need some more information

**Comment by mrajput-systango** [comment]
I am also facing the same issue. Can anyone help here, please?

**Comment by pedrovgs** [comment]
Hi @LalitSharma-Systango and @mrajput-systango your issue seems to be related to a bug I already fixed in the original Facebook library. It's already fixed by they didn't release the new version. We will have to wait until they publish the next release in order to update our library.
