### ISSUE TITLE
Running Screenshot Tests in Firebase Testlab

### ISSUE THREAD

**Issue by balachandarlinks** [Karumi/Shot#212]
Hi, Thanks for building this library. I successfully added screenshot tests to our project and now I want to run these screenshot tests in firebase testlab. When I upload the apk and test apk to firebase testlab, even though the test succeeds, I see failure to compare the screenshots in the logs as the reference screenshots are not available.

Firebase testlab don't have access to the project. So the reference screenshots need to be part of the APKs or pushed to device/emulator storage before running screenshot tests.

I found that it is supported in the [screenshot-tests-for-android](https://github.com/facebook/screenshot-tests-for-android) repo via a custom property called [referenceDir](https://github.com/facebook/screenshot-tests-for-android#running-with-a-remote-service). 

Is there anything similar to that exists in shot? Thanks in advance for your time.

Firebase Testlab Error Log:
```
03-30 03:56:34.714: E/System(6095): Unable to open zip file: /data/user/0/com.Xxx.yyy.debug/cache/hTYbT393.jar
03-30 03:56:34.716: E/System(6095): java.io.FileNotFoundException: File doesn't exist: /data/user/0/com.Xxx.yyy.debug/cache/hTYbT393.jar
03-30 03:56:34.716: E/System(6095): 	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
03-30 03:56:34.716: E/System(6095): 	at java.util.zip.ZipFile.<init>(ZipFile.java:152)
03-30 03:56:34.716: E/System(6095): 	at java.util.jar.JarFile.<init>(JarFile.java:160)
03-30 03:56:34.716: E/System(6095): 	at java.util.jar.JarFile.<init>(JarFile.java:97)
03-30 03:56:34.716: E/System(6095): 	at libcore.io.ClassPathURLStreamHandler.<init>(ClassPathURLStreamHandler.java:47)
03-30 03:56:34.716: E/System(6095): 	at dalvik.system.DexPathList$Element.maybeInit(DexPathList.java:702)
03-30 03:56:34.716: E/System(6095): 	at dalvik.system.DexPathList$Element.findResource(DexPathList.java:729)
03-30 03:56:34.716: E/System(6095): 	at dalvik.system.DexPathList.findResources(DexPathList.java:526)
03-30 03:56:34.716: E/System(6095): 	at dalvik.system.BaseDexClassLoader.findResources(BaseDexClassLoader.java:174)
03-30 03:56:34.716: E/System(6095): 	at java.lang.ClassLoader.getResources(ClassLoader.java:839)
03-30 03:56:34.716: E/System(6095): 	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:349)
03-30 03:56:34.716: E/System(6095): 	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:402)
03-30 03:56:34.716: E/System(6095): 	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:488)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.internal.platform.ServiceLoaderWrapper.loadService(ServiceLoaderWrapper.java:46)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.internal.platform.ServiceLoaderWrapper.loadSingleService(ServiceLoaderWrapper.java:69)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.internal.platform.util.TestOutputEmitter.<clinit>(TestOutputEmitter.java:27)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.internal.platform.util.TestOutputEmitter.addOutputProperties(TestOutputEmitter.java:69)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.espresso.GraphHolder.baseLayer(GraphHolder.java:12)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.espresso.Espresso.<clinit>(Espresso.java:2)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.espresso.Espresso.onIdle(Espresso.java:21)
03-30 03:56:34.716: E/System(6095): 	at com.karumi.shot.ScreenshotTest$DefaultImpls.waitForAnimationsToFinish(ScreenshotTest.kt:158)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest.waitForAnimationsToFinish(XxxCodeScreenshotTest.kt:13)
03-30 03:56:34.716: E/System(6095): 	at com.karumi.shot.ScreenshotTest$DefaultImpls.disableFlakyComponentsAndWaitForIdle(ScreenshotTest.kt:146)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest.disableFlakyComponentsAndWaitForIdle(XxxCodeScreenshotTest.kt:13)
03-30 03:56:34.716: E/System(6095): 	at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot(ScreenshotTest.kt:57)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest.compareScreenshot(XxxCodeScreenshotTest.kt:13)
03-30 03:56:34.716: E/System(6095): 	at com.karumi.shot.ScreenshotTest$DefaultImpls.compareScreenshot$default(ScreenshotTest.kt:52)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest$test$2.invoke(XxxCodeScreenshotTest.kt:20)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest$test$2.invoke(XxxCodeScreenshotTest.kt:13)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.uitest.Xxxcode.XxxCodeUiTestRobot.assert(XxxCodeUiTestRobot.kt:19)
03-30 03:56:34.716: E/System(6095): 	at com.Xxx.yyy.screenshottest.XxxCodeScreenshotTest.test(XxxCodeScreenshotTest.kt:19)
03-30 03:56:34.716: E/System(6095): 	at java.lang.reflect.Method.invoke(Native Method)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
03-30 03:56:34.716: E/System(6095): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
03-30 03:56:34.716: E/System(6095): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
03-30 03:56:34.716: E/System(6095): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
03-30 03:56:34.716: E/System(6095): 	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule$1.evaluate(MarkThatRulesRanRule.java:106)
03-30 03:56:34.716: E/System(6095): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
03-30 03:56:34.716: E/System(6095): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
03-30 03:56:34.716: E/System(6095): 	at org

```

**Comment by pedrovgs** [comment]
@balachandarlinks this repository contains several examples of how to configure Shot for GitHub actions and can be also used for Travis CI or any other similar environment. However, if you want to use Firebase test lab you'll have to use a custom solution and fetch the screenshots taken using some custom scripts we do not provide.

**Comment by balachandarlinks** [comment]
I ll check it out @pedrovgs. Thanks for your reponse 👍

**Comment by sanginovs** [comment]
i don't think you can use firebase test lab to verify screenshot tests. You can use it to generate screenshot tests. It uploads generated tests into Google Cloud. Then, you can fetch the generated screenshots and compare against the baseline screenshot using gradle task shot provides: `./gradlew executeScreenshotTests -PrunInstrumentation=false`.

**Comment by balachandarlinks** [comment]
Thanks for your comment @sanginovs. 

I thought of the suggested approach with firebase testlab. But we need to write tests that just take screenshots and then another set of tests that do the comparison between two set of screenshots. So I didn't go ahead with it as it will be hard to maintain.

I tried to run the tests in Gitlab CI. But unfortunately our Gitlab CI runners (using AWS instances) don't support KVM and so they can't run any of the recent emulators :| The one it was able to run was painfully slow and makes the test cases flaky. 

So unfortunately, I need to wait for KVM support in our CI to be able to utilise awesome screenshot tests :(

**Comment by SumeraMartin** [comment]
I ran into the same problem. I wonder if it wouldn't be possible to save screenshots to `androidTest/res/assets/` folder (either as images as or as zip file) instead of the directory outside of the apk. The test could then compare a result with an image taken from these assets and it would work even in the Firebase Test Lab. @pedrovgs Do you think that it would be possible? Or are there some other limitations that I'm not aware of?

**Comment by marcin-adamczewski** [comment]
@balachandarlinks @SumeraMartin Were you able to resolve the issue or take another approach to the problem?

**Comment by SumeraMartin** [comment]
@marcin-adamczewski sadly, I didn't find a way how to solve this issue. We set up a local server where tests are running.

**Comment by tdrhq** [comment]
I set up an example of using Shot with Firebase Test Lab in CI: https://github.com/screenshotbot/shot-example

(Full disclosure, there's some self-promotion here, since it's set up to upload screenshots to Screenshotbot, a tool I maintain. But you could in theory take some of the concepts from here to build a record/verify workflow without Screenshotbot)
