### ISSUE TITLE
Freemarker usage does not support Configuration Cache

### ISSUE THREAD

**Issue by chrisjenx** [Karumi/Shot#231]
Shot doesn't support Configuration Cache.

See undeclared sys prop link below, basically stop reading `file.encoding` as this could change busting caching everytime.

### Expected behaviour
https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read

### Actual behaviour
- Plugin 'shot': read system property 'file.encoding'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read

### Steps to reproduce
./gradlew --configuration-cache

### Version of the library
5.10.5

**Comment by yogurtearl** [comment]
With 
```
cd shot-consumer
./gradlew --configuration-cache
```

Looks like the problem is in Freemarker. 
Doesn't look like there is a way to make Freemarker NOT read that property, so probably need a change to Freemarker to fix this. 
https://github.com/apache/freemarker/blob/v2.3.31/src/main/java/freemarker/template/Configuration.java#L2964


Stacktrace is: 
```
org.gradle.api.InvalidUserCodeException: Read system property 'file.encoding'
	at org.gradle.configurationcache.SystemPropertyAccessListener.systemPropertyQueried(SystemPropertyAccessListener.kt:92)
	at org.gradle.internal.classpath.Instrumented.systemProperty(Instrumented.java:83)
	at freemarker.template.utility.SecurityUtilities$2.run(SecurityUtilities.java:53)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at freemarker.template.utility.SecurityUtilities.getSystemProperty(SecurityUtilities.java:48)
	at freemarker.template.Configuration.getJVMDefaultEncoding(Configuration.java:2964)
	at freemarker.template.Configuration.getDefaultDefaultEncoding(Configuration.java:2960)
	at freemarker.template.Configuration.<init>(Configuration.java:583)
	at com.karumi.shot.reports.ExecutionReporter.<init>(ExecutionReporter.scala:15)
	at com.karumi.shot.ShotPlugin.shot$lzycompute(ShotPlugin.scala:39)
	at com.karumi.shot.ShotPlugin.shot(ShotPlugin.scala:31)
	at com.karumi.shot.ShotPlugin.configureAdb(ShotPlugin.scala:57)
	at com.karumi.shot.ShotPlugin.$anonfun$apply$1(ShotPlugin.scala:49)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:100)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:153)
```

**Comment by chrisjenx** [comment]
Dang, @yogurtearl do you know what Freemarker is used for? I.e. could we swap it out with something else?

**Comment by pedrovgs** [comment]
Hi @chrisjenx and @yogurtearl 😃  Thanks for reporting! The usage of ``freemarker`` is needed for our HTML reports. We could replace this lib with any other alternative. Looks like the [latest version of this lib is also reading](https://github.com/apache/freemarker/blob/2.3-gae/src/main/java/freemarker/template/Configuration.java#L2964) that property so we would need to change the templates engine we use to fix this issue and ensure the new one is working as expected. This is not a trivial change and right now I'm working on a different task. It could be great if any external contributor can take care of this one. Thanks!

**Comment by chrisjenx** [comment]
Looking at the implementation of freemarker, it's actually a poor impl on their side instead of lazy init the encoding when needed it reads it when the class is created, so even though you set it from gradle it still calls it first. 
Really we need to patch Freemarker, not sure how receptive they will be....
