### ISSUE TITLE
Failure executing task executeScreenshotTests due to SAXParseException

### ISSUE THREAD

**Issue by juange87** [Karumi/Shot#33]
### Expected behaviour

`executeScreenshotTests` or `executeScreenshotTests -Precord` should work as expected

### Actual behaviour

Exception happens executing those tasks:

```
* What went wrong:
Execution failed for task ':app:executeScreenshotTests'.
> org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; El contenido no est? permitido en el pr?logo.
```

### Version of the library

Tested on **1.0.0**, **0.3.0**, **0.2.0**

### Extended Stacktrace

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:executeScreenshotTests'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.internal.UncheckedException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; El contenido no est? permitido en el pr?logo.
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:731)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:705)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; El contenido no est? permitido en el pr?logo.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
        at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
        at scala.xml.XML$.loadXML(XML.scala:60)
        at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
        at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
        at scala.xml.XML$.loadString(XML.scala:60)
        at com.karumi.shot.xml.ScreenshotsSuiteXmlParser$.parseScreenshotSize(ScreenshotsSuiteXmlParser.scala:57)
        at com.karumi.shot.Shot.$anonfun$readScreenshotsMetadata$1(Shot.scala:121)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
        at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:375)
        at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:375)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
        at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
        at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:414)
        at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:56)
        at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:555)
        at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:555)
        at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:80)
        at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:956)
        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
        at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:951)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
        Suppressed: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; El contenido no est? permitido en el pr?logo.
                at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
                at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
                at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
                at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
                at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
                at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
                at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
                at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
                at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
                at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
                at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
                at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
                at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
                at scala.xml.XML$.loadXML(XML.scala:60)
                at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
                at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
                at scala.xml.XML$.loadString(XML.scala:60)
                at com.karumi.shot.xml.ScreenshotsSuiteXmlParser$.parseScreenshotSize(ScreenshotsSuiteXmlParser.scala:57)
                at com.karumi.shot.Shot.$anonfun$readScreenshotsMetadata$1(Shot.scala:121)
                at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
                at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
                at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
                at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
                at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
                at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
                at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
                at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
                at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
                at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
                at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
                at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
                at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
                at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
                at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
                at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
                at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
                at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
                Suppressed: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; El contenido no est? permitido en el pr?logo.
                        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
                        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
                        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
                        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
                        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
                        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
                        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
                        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
                        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
                        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
                        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
                        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
                        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
                        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
                        at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
                        at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
                        at scala.xml.XML$.loadXML(XML.scala:60)
                        at scala.xml.factory.XMLLoader.loadString(XMLLoader.scala:60)
                        at scala.xml.factory.XMLLoader.loadString$(XMLLoader.scala:60)
                        at scala.xml.XML$.loadString(XML.scala:60)
                        at com.karumi.shot.xml.ScreenshotsSuiteXmlParser$.parseScreenshotSize(ScreenshotsSuiteXmlParser.scala:57)
                        at com.karumi.shot.Shot.$anonfun$readScreenshotsMetadata$1(Shot.scala:121)
                        at scala.collection.parallel.AugmentedIterableIterator.map2combiner(RemainsIterator.scala:112)
                        at scala.collection.parallel.AugmentedIterableIterator.map2combiner$(RemainsIterator.scala:109)
                        at scala.collection.parallel.immutable.ParVector$ParVectorIterator.map2combiner(ParVector.scala:62)
                        at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
                        at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
                        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
                        at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
                        at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
                        at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
                        at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
                        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:149)
                        ... 7 more
```

**Comment by pedrovgs** [comment]
Hi @juange87 thanks for reporting this bug. Just reading the stack trace makes me think this bug has to be related to the parsing of the XML metadata file the runner generates containing information about the tests execution. Could you please run the tests on any device or emulator you use, wait until the library fails and get a copy of the content you'll find at ``/tmp/shot/``? It has to be related to the document encoding or something similar, but without the metadata file I won't be able to fix it.

**If the content of this folder contains sensitive information for you or your company review the content or share it directly with me through email. You can also create a new project on GitHub reproducing the error.**

**Comment by juange87** [comment]
Ok, I will try to do during the day.

I have more info related to this. 

While setting up Shot, I made a change regarding this:

<img width="921" alt="captura de pantalla 2018-01-24 a las 8 41 46" src="https://user-images.githubusercontent.com/623411/35320012-8c0207c0-00e2-11e8-9936-e2970279d66f.png">

I changed the version to **0.5.0** (we had set Screenshot testing but It was not merged due to we hadn't a proper CI to run the Screenshot tests)

 ```
androidTestCompile ('com.facebook.testing.screenshot:core:0.5.0') {
    exclude group: 'com.crittercism.dexmaker', module: 'dexmaker'
    exclude group: 'com.crittercism.dexmaker', module: 'dexmaker-dx'
  }
```

Last night at home I tried to record the tests again but changing this version to 0.4.2, and it worked as expected.

What make me think is, we are dropping the Facebook Screenshot testing configuration in favor of Shot, so the `androidTestCompile ('com.facebook.testing.screenshot:core:0.4.2')` dependency should not affect us but if we remove it, we got the `DexException`

**Comment by AOrobator** [comment]
I can reproduce this issue 100% of the time, and I've made a sample repo that you can take a look at here:  https://github.com/AOrobator/ScreenshotTest.

Originally posted as an issue here: https://github.com/Karumi/Shot/issues/34

**Comment by pedrovgs** [comment]
Thanks @AOrobator this repository is really helpful! Could you try by removing the facebook plugin from your classpath? Shot add all the dependencies needed to run your screenshot tests including the facebook lib.

**Comment by AOrobator** [comment]
@pedrovgs Thanks that got me a bit further. Now I'm running into a separate issue which I've filed here: https://github.com/Karumi/Shot/issues/35

**Comment by eduardb** [comment]
I ran as well into this issue, it seems that Shot is not working with version 0.5.0 of the facebook plugin. Which is a shame, since that version would solve the issue #35. I'm looking forward to seeing the update to make it work though :)

**Comment by pedrovgs** [comment]
@eduardb @AOrobator @juange87 we've fixed this issue and provided support for the latest versions of the Facebook core library. I'm about to release a new version with @Serchinastico and @tonilopezmr contributions.

**Comment by eduardb** [comment]
Thanks for the notice, Pedro! :)

**Comment by pedrovgs** [comment]
You are welcome @eduardb are you using Shot for a personal or company project? We'd like to know if we have some users 😃

**Comment by eduardb** [comment]
Hehe :) I am using it for a personal project, I started it very recently, and it's advancing slowly since I am working on it in my (limited) spare time. But I got introduced to the concept of screenshot testing at work on the web application we are working on, and it got me really excited to be able to do it on Android as well in such an easy way. Good job, btw! :)

**Comment by juange87** [comment]
Congrats team!! 💪
