### ISSUE TITLE
Generation of screenshots throws NPE with `runInstrumentation false`

### ISSUE THREAD

**Issue by charlesdurham** [Karumi/Shot#69]
Looks like it's because https://github.com/Karumi/Shot/blob/64d160291ed1564307507a5830bbb56e5e932d51/core/src/main/scala/com/karumi/shot/Shot.scala#L136 returns null if the directory doesn't exist.

Worked around by creating `/screenshots/screenshot-default/`.

```
Caused by: java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:195)
	at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:191)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:246)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:191)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:191)
	at com.karumi.shot.Shot.readScreenshotsMetadata(Shot.scala:137)
	at com.karumi.shot.Shot.recordScreenshots(Shot.scala:48)
	at com.karumi.shot.tasks.ExecuteScreenshotTests.executeScreenshotTests(Tasks.scala:56)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

**Comment by charlesdurham** [comment]
Actually, I seem to have to generate this dir every time. FWIW I am also using `runInstrumentation = false`.

**Comment by charlesdurham** [comment]
Nevermind, I'm a fool and wasn't copying the screenshots off FTL device correctly.

**Comment by julioz** [comment]
We are also running into this problem when following this project's README and setting 
```
shot {
  runInstrumentation = false
}
```

Creating a `screenshots` directory in the following structure still didn't help:
```
my-module
├── build.gradle
├── screenshots
│   └── screenshot-default
└── src
    ├── androidTest
    └── main
```

Getting the following error when running `executeScreenshotTests -Precord`:

```
💾  Saving screenshots.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mymodule:debugExecuteScreenshotTests'.
> java.lang.NullPointerException (no error message)
```

```
Caused by: java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:195)
        at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:191)
        at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:246)
        at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
        at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:191)
        at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
        at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
        at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:191)
        at com.karumi.shot.Shot.readScreenshotsMetadata(Shot.scala:175)
        at com.karumi.shot.Shot.recordScreenshots(Shot.scala:48)
        at com.karumi.shot.tasks.ExecuteScreenshotTests.executeScreenshotTests(Tasks.scala:68)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
```

@pedrovgs Can you please advise?

**Comment by pedrovgs** [comment]
@julioz if you disable ``runInstrumentation`` you'll have to run instrumentation tests manually before executing Shot. This error is something we have to improve to specify there were no screenshots to pull.
